export const cities = [
  "Adana", "Adıyaman", "Afyonkarahisar", "Ağrı", "Amasya", "Ankara", "Antalya", "Artvin", "Aydın", "Balıkesir",
  "Bilecik", "Bingöl", "Bitlis", "Bolu", "Burdur", "Bursa", "Çanakkale", "Çankırı", "Çorum", "Denizli",
  "Diyarbakır", "Edirne", "Elazığ", "Erzincan", "Erzurum", "Eskişehir", "Gaziantep", "Giresun", "Gümüşhane",
  "Hakkari", "Hatay", "Isparta", "Mersin", "İstanbul", "İzmir", "Kars", "Kastamonu", "Kayseri", "Kırklareli",
  "Kırşehir", "Kocaeli", "Konya", "Kütahya", "Malatya", "Manisa", "Kahramanmaraş", "Mardin", "Muğla", "Muş",
  "Nevşehir", "Niğde", "Ordu", "Rize", "Sakarya", "Samsun", "Siirt", "Sinop", "Sivas", "Tekirdağ",
  "Tokat", "Trabzon", "Tunceli", "Şanlıurfa", "Uşak", "Van", "Yozgat", "Zonguldak", "Aksaray", "Bayburt",
  "Karaman", "Kırıkkale", "Batman", "Şırnak", "Bartın", "Ardahan", "Iğdır", "Yalova", "Karabük", "Kilis",
  "Osmaniye", "Düzce"
];

export const universities = [
  "Fırat Üniversitesi",
  "Orta Doğu Teknik Üniversitesi (ODTÜ)",
  "İstanbul Teknik Üniversitesi (İTÜ)",
  "Boğaziçi Üniversitesi",
  "Yıldız Teknik Üniversitesi (YTÜ)",
  "Hacettepe Üniversitesi",
  "Ankara Üniversitesi",
  "Ege Üniversitesi",
  "Dokuz Eylül Üniversitesi",
  "İstanbul Üniversitesi",
  "Koç Üniversitesi",
  "Sabancı Üniversitesi",
  "Bilkent Üniversitesi",
  "TOBB Ekonomi ve Teknoloji Üniversitesi",
  "Galatasaray Üniversitesi",
  "Marmara Üniversitesi",
  "Gazi Üniversitesi",
  "Anadolu Üniversitesi",
  "Akdeniz Üniversitesi",
  "Karadeniz Teknik Üniversitesi (KTÜ)",
  "Gebze Teknik Üniversitesi",
  "Sakarya Üniversitesi",
  "Kocaeli Üniversitesi",
  "Selçuk Üniversitesi",
  "Çukurova Üniversitesi",
  "İnönü Üniversitesi",
  "Atatürk Üniversitesi",
  "Erciyes Üniversitesi",
  "Pamukkale Üniversitesi",
  "Süleyman Demirel Üniversitesi",
  "Bursa Uludağ Üniversitesi",
  "Dicle Üniversitesi",
  "Ondokuz Mayıs Üniversitesi",
  "Trakya Üniversitesi",
  "Muğla Sıtkı Koçman Üniversitesi",
  "Mersin Üniversitesi",
  "Aydın Adnan Menderes Üniversitesi",
  "Balıkesir Üniversitesi",
  "Çanakkale Onsekiz Mart Üniversitesi",
  "Manisa Celal Bayar Üniversitesi",
  "Kırıkkale Üniversitesi",
  "Zonguldak Bülent Ecevit Üniversitesi",
  "Recep Tayyip Erdoğan Üniversitesi",
  "Kütahya Dumlupınar Üniversitesi",
  "Uşak Üniversitesi",
  "Bahçeşehir Üniversitesi",
  "Yeditepe Üniversitesi",
  "Kadir Has Üniversitesi",
  "Özyeğin Üniversitesi",
  "TED Üniversitesi",
  "Diğer"
];

export const departments = [
  "Yazılım Mühendisliği",
  "Bilgisayar Mühendisliği",
  "Yönetim Bilişim Sistemleri",
  "Yapay Zeka Mühendisliği",
  "Elektrik-Elektronik Mühendisliği",
  "Endüstri Mühendisliği",
  "Makine Mühendisliği",
  "İnşaat Mühendisliği",
  "Grafik Tasarım",
  "Görsel İletişim Tasarımı",
  "Endüstriyel Tasarım",
  "İç Mimarlık ve Çevre Tasarımı",
  "Mimarlık",
  "İşletme",
  "İktisat",
  "Maliye",
  "Finans ve Bankacılık",
  "Uluslararası Ticaret ve Lojistik",
  "İnsan Kaynakları Yönetimi",
  "Pazarlama",
  "Halkla İlişkiler ve Tanıtım",
  "İletişim Tasarımı ve Yönetimi",
  "Yeni Medya ve İletişim",
  "Matematik",
  "İstatistik",
  "Fizik",
  "Kimya",
  "Moleküler Biyoloji ve Genetik",
  "Beslenme ve Diyetetik",
  "Fizyoterapi ve Rehabilitasyon",
  "Psikoloji",
  "Sosyoloji",
  "İngiliz Dili ve Edebiyatı",
  "Mütercim Tercümanlık",
  "Okul Öncesi Öğretmenliği",
  "Sınıf Öğretmenliği",
  "Rehberlik ve Psikolojik Danışmanlık (PDR)",
  "Diğer"
];
